-- DougHub seasonal games + leaderboard
-- Run once in the Supabase SQL Editor.

create table if not exists public.seasonal_game_settings (
  id integer primary key,
  enabled boolean not null default false,
  season text not null default 'summer',
  updated_at timestamptz not null default now()
);

insert into public.seasonal_game_settings (id, enabled, season)
values (1, false, 'summer')
on conflict (id) do nothing;

alter table public.seasonal_game_settings enable row level security;

drop policy if exists "Seasonal settings are public" on public.seasonal_game_settings;
create policy "Seasonal settings are public"
on public.seasonal_game_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can update seasonal settings" on public.seasonal_game_settings;
create policy "Admins can update seasonal settings"
on public.seasonal_game_settings
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.is_admin = true
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.is_admin = true
  )
);

drop policy if exists "Admins can insert seasonal settings" on public.seasonal_game_settings;
create policy "Admins can insert seasonal settings"
on public.seasonal_game_settings
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.is_admin = true
  )
);

create table if not exists public.seasonal_game_scores (
  id bigint generated by default as identity primary key,
  game_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  score integer not null check (score >= 0 and score <= 10000),
  created_at timestamptz not null default now()
);

create index if not exists seasonal_game_scores_game_score_idx
on public.seasonal_game_scores (game_key, score desc, created_at asc);

alter table public.seasonal_game_scores enable row level security;

drop policy if exists "Seasonal scores are public" on public.seasonal_game_scores;
create policy "Seasonal scores are public"
on public.seasonal_game_scores
for select
to anon, authenticated
using (true);

drop policy if exists "Users can submit their own seasonal scores" on public.seasonal_game_scores;
create policy "Users can submit their own seasonal scores"
on public.seasonal_game_scores
for insert
to authenticated
with check (
  user_id = (select auth.uid())
);

revoke update, delete on public.seasonal_game_scores from anon, authenticated;
grant select on public.seasonal_game_scores to anon, authenticated;
grant insert on public.seasonal_game_scores to authenticated;
